# Generated by Django 5.1.7 on 2025-03-31 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025,
                    3,
                    31,
                    20,
                    55,
                    13,
                    692590,
                    tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]
