# Generated by Django 5.1.7 on 2025-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("table", "date", "time"), name="unique_booking"
            ),
        ),
    ]
